apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
    name: tejas
spec:
    groups:
    - system:authenticated
    usages:
    - digital signature
    - key encipherment
    - server auth
    request:
      # here base64 user.csr file 
