apiVersion: v1
kind: PersistentVolume
metadata:
     name: pv-vol1
spec:
     accessMode:
     - ReadWriteOnce
     capacity:
       storage: 1Gi
     hostPath:
       path: /tmp/data
#    awsElasticBlockStore:
#      volumeID: <volume-ID>
#      fsType: ext4     
